version: '3.9'
networks:
  nginxproxy-net:
    external: true

services:
  magento:
    build: 
      context: .
      dockerfile: ./dockerfiles/magento.dockerfile
    volumes:
      - ./src:/var/www/html:rw
      - nginx:/etc/nginx/http.d:ro
    networks:
      - "nginxproxy-net"
    ports:
      - '80:80'
    environment:
      - VIRTUAL_HOST=hama.local.test
      - VIRTUAL_PORT=80
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer-utility.dockerfile
    volumes: 
      - ./src:/var/www/html      

volumes:
  nginx: