version: '3.9'
services:
  nginx:
    build: 
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./magento:/var/www/html/magento
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf.ro  
    #depends_on:
    #  - php
    #  - mysql
  php:
    build: 
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      - ./magento:/var/www/html/magento 
  mysql:
    image: mysql:latest
    env_file:
      - ./env/mysql.env
  magento:
    build: 
        context: ./dockerfiles
        dockerfile: magento.dockerfile
    volumes:
      - ./magento:/var/www/html/magento
    env_file:
      - ./env/magento.env  
  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./magento:/var/www/html/magento
  magerun:
    build: 
        context: ./dockerfiles
        dockerfile: magerun.dockerfile
    volumes:
      - ./magento:/var/www/html/magento
  elasticsearch:
    image: elasticsearch:8.5.3
    environment:
      - discovery.type=single-node