#!/bin/bash

CONTAINER_NAME=$1

docker exec -w /bitnami/magento -i $CONTAINER_NAME php bin/magento sampledata:deploy
docker exec -w /bitnami/magento -i $CONTAINER_NAME php bin/magento setup:upgrade
docker exec -w /bitnami/magento  -i $CONTAINER_NAME php bin/magento setup:di:compile
docker exec -w /bitnami/magento  -i $CONTAINER_NAME php bin/magento indexer:reindex 
docker exec -w /bitnami/magento -i $CONTAINER_NAME php bin/magento setup:static-content:deploy -f
docker exec -w /bitnami/magento  -i $CONTAINER_NAME php bin/magento cache:flush
 
# Fix permission
docker exec -w /bitnami/magento  -i $CONTAINER_NAME chown -R daemon.root .
