#!/bin/bash

CONTAINER_NAME=$1

# You can change memory limit if you want set a limit. -1 = Infinite Memory Limit
docker exec -w /bitnami/magento -i $CONTAINER_NAME php -d memory_limit=-1  bin/magento sampledata:deploy
docker exec -w /bitnami/magento -i $CONTAINER_NAME php bin/magento setup:upgrade
docker exec -w /bitnami/magento  -i $CONTAINER_NAME php bin/magento setup:di:compile
docker exec -w /bitnami/magento  -i $CONTAINER_NAME php bin/magento indexer:reindex 
docker exec -w /bitnami/magento -i $CONTAINER_NAME php bin/magento setup:static-content:deploy -f
docker exec -w /bitnami/magento  -i $CONTAINER_NAME php bin/magento cache:flush
 
# Fix permission
docker exec -w /bitnami/magento  -i $CONTAINER_NAME chown -R daemon.root .
