version: "3.9"

networks:
  dbnetwork:
    external: true
  elasticnet:
    external: true

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    container_name: mariadb
    env_file:
      - ./env/mariadb.env
    volumes:
      - "mariadb_data:/bitnami/mariadb"
    networks:
      - "dbnetwork"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    networks:
      - "dbnetwork"
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - "elasticsearch_data:/bitnami/elasticsearch/data"
    env_file:
      - ./env/elastic.env
    networks:
      - "elasticnet"

volumes:
  mariadb_data:
    driver: local
  elasticsearch_data:
    driver: local
