#!/usr/bin/env bash

 if [[ z $PROJECT_NAME || -z $BASE_URL  || -z $DB_NAME || -z $DB_USER || -Z $DB_PASSWORD || -z $ADMIN_EMAIL]] then
    echo "Some value are missing, please check."
    echo "Please compile env file before start container"
 fi

cd /var/www/html

find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} +
find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} +
chown -R www-data:www-data .

&& chmod u+x ./bin/magento \
&& php -f ./bin/magento setup:install --base-url=$BASE_URL \
    --db-host=mysql \
    --db-name=$DB_NAME \
    --db-user=DB_USER \
    --db-password=$DB_PASSWORD \
    --admin-firstname=Magento \
    --admin-lastname=Commerce \
    --admin-email=$ADMIN_EMAIL \
    --admin-user=admin \
    --admin-password=Admin123 \
    --language=en_US \
    --currency=USD \
    --timezone=America/Chicago \
    --use-rewrites=1 \
    --backend-frontname=admin \
    --elasticsearch-host=elasticsearch;

&& echo "Magento setup:install done"    

php -f ./bin/magento setup:upgrade \
&& php -f ./bin/magento setup:di:compile \
&& php -f ./bin/magento deploy:mode:set developer \
&& php -f ./bin/magento setup:static-content:deploy -f\
&& php -f ./bin/magento indexer:reindex \
&& php -f ./bin/magento cache:clean \
&& php -f ./bin/magento cache:flush;

clear 
&& echo "Magento was installed: Yes."