version: "3.9"

networks:
  nginxproxy-net:
    external: true

services:
  reverse-proxy:
    build:
        context: .
        dockerfile: reverse-proxy.dockerfile
    container_name: "reverse-proxy"
    volumes:
        - "/run/docker.sock:/tmp/docker.sock:ro"
        - "reversevolume:/etc/nginx"
    restart: "always"
    networks:
        - "nginxproxy-net"
    ports:
        - "80:80"
        - "443:443"

volumes:
  reversevolume:
