version: "3.7"
services:
  reverse-proxy:
    image: "nginxproxy/nginx-proxy:latest"
    container_name: "reverse-proxy"
    volumes:
        - "/run/docker.sock:/tmp/docker.sock:ro"
    restart: "always"
    networks: 
        - "nginxproxy-net"
    ports:
        - "80:80"
        - "443:443"