version: "3.9"
networks:
  nginxproxy-net:
    external: true
  dbnetwork:
    external: true
  elasticnet:
    external: true

services:
  service_name:
    image: docker.io/bitnami/magento:${MAGENTO_VERSION}
    container_name: container-name
    env_file:
      - ./env/magento.env
    volumes:
      - "magento_data:/bitnami/magento"
      - "./auth/auth.json:/bitnami/magento/auth.json:rw"
    networks:
      - "nginxproxy-net"
      - "dbnetwork"
      - "elasticnet"
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local
